/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChefiaRouteImport } from './routes/chefia'
import { Route as AtividadesRouteImport } from './routes/atividades'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtividadesIdRouteImport } from './routes/atividades.$id'

const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefiaRoute = ChefiaRouteImport.update({
  id: '/chefia',
  path: '/chefia',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesRoute = AtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesIdRoute = AtividadesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AtividadesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRouteWithChildren
  '/chefia': typeof ChefiaRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/atividades/$id': typeof AtividadesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRouteWithChildren
  '/chefia': typeof ChefiaRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/atividades/$id': typeof AtividadesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRouteWithChildren
  '/chefia': typeof ChefiaRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/atividades/$id': typeof AtividadesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atividades'
    | '/chefia'
    | '/dashboard'
    | '/login'
    | '/perfil'
    | '/atividades/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atividades'
    | '/chefia'
    | '/dashboard'
    | '/login'
    | '/perfil'
    | '/atividades/$id'
  id:
    | '__root__'
    | '/'
    | '/atividades'
    | '/chefia'
    | '/dashboard'
    | '/login'
    | '/perfil'
    | '/atividades/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtividadesRoute: typeof AtividadesRouteWithChildren
  ChefiaRoute: typeof ChefiaRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chefia': {
      id: '/chefia'
      path: '/chefia'
      fullPath: '/chefia'
      preLoaderRoute: typeof ChefiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades': {
      id: '/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AtividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades/$id': {
      id: '/atividades/$id'
      path: '/$id'
      fullPath: '/atividades/$id'
      preLoaderRoute: typeof AtividadesIdRouteImport
      parentRoute: typeof AtividadesRoute
    }
  }
}

interface AtividadesRouteChildren {
  AtividadesIdRoute: typeof AtividadesIdRoute
}

const AtividadesRouteChildren: AtividadesRouteChildren = {
  AtividadesIdRoute: AtividadesIdRoute,
}

const AtividadesRouteWithChildren = AtividadesRoute._addFileChildren(
  AtividadesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtividadesRoute: AtividadesRouteWithChildren,
  ChefiaRoute: ChefiaRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
